---
language: node_js
node_js:
  - "0.12"
  - "4.2"
  - "6"

dist: trusty
sudo: required

branches:
  only:
    - master
    - auto
    - /^greenkeeper.*$/

cache:
  directories:
    - node_modules

env:
  - NPM_SCRIPT=node-test

matrix:
  fast_finish: true
  include:
  - node_js: "6"
    env: NPM_SCRIPT=lint

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
  - npm install -g npm@^2

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm run-script $NPM_SCRIPT
